In [40]:
#1.

import numpy as np
def add_matrix(x,y):
    if np.shape(x)==np.shape(y):
        
        mat_result = np.zeros(np.shape(x))
        for i in range(len(x)):
            for j in range(len(x[i])):
                mat_result[i][j]= x[i][j] + y[i][j]
        print(mat_result)
    else:
        print("invilid matrix")

In [85]:
#2.

import numpy as np
def multiplication_matrix(x,y):
    mat_result = np.zeros((np.shape(x)[0],np.shape(y)[1]))
    if np.shape(x)[0]==np.shape(y)[1]:
        
        for i in range(int(np.shape(x)[1])):
            for j in range(int(np.shape(y)[0])):
                for k in range(int(np.shape(y)[1])):
                    
                    mat_result[i][j] += x[i][k] * y[k][j]
        print(mat_result)

x = [[21,51, 10, 71],
     [51,92, 42, 22],
     [3, 53, 83, 23],
     [41, 58, 66, 74]]
y = [[1, 10, 44, 11],
     [33, 85, 1, 2],
     [3, 12, 32, 8],
     [1, 652, 3, 76]]

multiplication_matrix(x,y)

[[ 1805. 50957.  1508.  5809.]
 [ 3235. 23178.  3746.  2753.]
 [ 2024. 20527.  2910.  2551.]
 [ 2227. 54380.  4196.  6719.]]


In [103]:
#3.

def transpose_matrix(x):
    mat_result = np.zeros((np.shape(x)[1],np.shape(x)[0]))
    
    for i in range(len(x)):
        for j in range(len(x[0])):
            mat_result[j][i] = x[i][j]
            
    print(mat_result)
        

In [ ]:
#4.

my_str = input("enter a sentence")

words = [word.lower() for word in my_str.split()]
words.sort()
print("The sorted words are:")
for i in words:
   print(i)

In [ ]:
#5.

punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

no_punct = ""
for i in my_str:
   if i not in punctuations:
       no_punct = no_punct + i

print(no_punct)